require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-thread_safety
AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - lib/proto/**/*
    - Gemfile.lock
Naming/AccessorMethodName:
  Exclude:
    - app/controllers/**/*
