FROM ruby:2.7.2-alpine
ENV LANG C.UTF-8

RUN apk add --no-cache build-base libxslt-dev libxml2-dev tzdata

WORKDIR /myapp

COPY Gemfile Gemfile.lock /myapp/
# @see https://github.com/protocolbuffers/protobuf/issues/2335#issuecomment-579913357
RUN bundle config build.google-protobuf --with-cflags=-D__va_copy=va_copy && \
    BUNDLE_FORCE_RUBY_PLATFORM=1 bundle install -j4

COPY . /myapp

EXPOSE 3000
